[package]
name = "CRMonitor"
version = "0.3.0"
edition = "2021"

[dependencies]
tray-icon = "0.13"
tao = "0.28"
image = "0.25"
sysinfo = "0.30"
cfg-if = "1.0"

[features]
linux-disk = ["procfs"]

[target.'cfg(target_os = "linux")'.dependencies]
procfs = { version = "0.16", optional = true }

# Windows GDI API (아주 가벼움)
[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.52", features = [
  "Win32_Foundation",
  "Win32_UI_WindowsAndMessaging",
  "Win32_Graphics_Gdi",
  "Win32_System_LibraryLoader",
  "Win32_NetworkManagement_IpHelper",
  "Win32_NetworkManagement_Ndis",   # ← GetIfTable2 / MIB_IF_TABLE2에 필요
  "Win32_Storage_FileSystem",       # ← CreateFileW 등에 필요
  "Win32_System_IO"
] }


[[bin]]
name = "CRMonitor"
path = "src/main.rs"
